---
title: "Final Project"
author: Leo Liu
output: github_document
---

```{r}
library(tidyverse)
library(purrr)
library(broom)
library(modelr)
```

```{r}
wine_130k = read_csv("./wine_data/winemag-data-130k-v2.csv")
wine_150k = read_csv("./wine_data/winemag-data_first150k.csv")
```

We will be using the wine_150k dataset from now on.
```{r}
wine_150k = wine_150k %>% 
  janitor::clean_names() %>% 
  select(country, points, price, variety) %>% 
  mutate(country = factor(country),
         variety = factor(variety))

# scatter plot 
wine_150k %>% 
  ggplot(aes(x = points, y = price, color = country)) +
  geom_point()

fit = lm(price ~ points, data = wine_150k)
tidy(fit)

modelr::add_residuals(wine_150k,
                      fit) %>% 
  ggplot(aes(x = points, y = resid)) +
  geom_point()

lm(price ~ points + country + variety, data = wine_150k) %>% 
  tidy()

wine_150k %>% 
  modelr::bootstrap(1000, id = "strap_number") %>% 
  mutate(
    models = map(.x = strap, ~lm(price ~ points, data = .x)),
    results = map(models, tidy)) %>% 
  select(strap_number, results) %>% 
  unnest(results) %>%
  group_by(term) %>% 
  summarize(
    mean_est = mean(estimate),
    sd_est = sd(estimate)
  )
  

```


```{r}


```



