---
title: "Reviews of US Wines"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include = FALSE}
library(tidyverse)
library(patchwork)
library(plotly)
library(flexdashboard)
```

<br/>

### Top 20 US Wineries

```{r Top 20 US Wineries Box Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(points, country, winery, variety, points_avg_variety, points_avg_winery) %>% 
  filter(country == "US") %>% 
  mutate(winery = fct_reorder(winery, desc(points_avg_winery))) %>% 
  filter(as.numeric(winery) <= 20) %>% 
  arrange(winery) %>% 
  plot_ly(
    x = ~winery, y = ~points, color = ~factor(winery),
    type = "box", colors = "viridis") %>%
  layout(
    xaxis = list(title = "US Wineries"),
    yaxis = list(title = "Wine Points"),
    title = "Top 20 US Wineries: Highest Professional Recognition")
```

### Bottom 20 US Wineries

```{r Bottom 20 US Wineries Box Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(points, country, winery, variety, points_avg_variety, points_avg_winery) %>% 
  filter(country == "US") %>% 
  mutate(winery = fct_reorder(winery, points_avg_winery)) %>% 
  filter(as.numeric(winery) <= 20) %>% 
  arrange(winery) %>% 
  plot_ly(
    x = ~winery, y = ~points, color = ~factor(winery),
    type = "box", colors = "viridis") %>%
  layout(
    xaxis = list(title = "US Wineries"),
    yaxis = list(title = "Wine Points"),
    title = "Bottom 20 US Wineries: Lowest Professional Recognition")
```

<br/>

### Top 10 Grapes for US Wines

```{r Most Favorable US Grapes Violin Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(points, country, winery, variety, points_med_variety, points_med_winery) %>% 
  filter(country == "US") %>% 
  mutate(variety = fct_reorder(variety, desc(points_med_variety))) %>% 
  filter(as.numeric(variety) <= 10) %>% 
  arrange(variety) %>% 
  plot_ly(
    x = ~variety, y = ~points, color = ~factor(variety),
    type = "violin", colors = "viridis") %>%
  layout(
    xaxis = list(title = "Grapes for US Wines"),
    yaxis = list(title = "Wine Points"),
    title = "Most Favorable 10 Grapes for US Wines: Highest Professional Recognition")
```

<br/>

### Bottom 10 Grapes for US Wines

```{r Least Favorable US Grapes Violin Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(points, country, winery, variety, points_med_variety, points_med_winery) %>% 
  filter(country == "US") %>% 
  mutate(variety = fct_reorder(variety, points_med_variety)) %>% 
  filter(as.numeric(variety) <= 10) %>% 
  arrange(variety) %>% 
  plot_ly(
    x = ~variety, y = ~points, color = ~factor(variety),
    type = "violin", colors = "viridis") %>%
  layout(
    xaxis = list(title = "Grapes for US Wines"),
    yaxis = list(title = "Wine Points"),
    title = "Least Favorable 10 Grapes for US Wines: Lowest Professional Recognition")
```

