---
title: "Reviews of American Wines"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include = FALSE}
library(tidyverse)
library(patchwork)
library(plotly)
library(flexdashboard)

knitr::opts_chunk$set(
	fig.width = 10, 
  fig.asp = .6,
  out.width = "100%"
)
```

<br/>

### American Countries Comparison

```{r American Countries Bar Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(country, points_avg_country) %>% 
  filter(country %in% c("Argentina", "Brazil", "Canada", "Chile", "Mexico", "Uruguay", "US")) %>% 
  mutate(country = fct_reorder(country, desc(points_avg_country))) %>% 
  unique() %>% 
  mutate(text_label = str_c("Country: ", country, "\nAverage Points: ", points_avg_country)) %>% 
  plot_ly(
    x = ~country, y = ~points_avg_country, color = ~factor(country), text = ~text_label,
    type = "bar", colors = "viridis") %>%
  layout(
    xaxis = list(title = "American Countries"),
    yaxis = list(title = "Average Wine Points", range = (c(80,88))),
    title = "Average Wine Points of American Countries")
```

<br/>

### Top 20 American Wineries

```{r Top 20 American Wineries Box Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(points, country, winery, variety, points_avg_variety, points_avg_winery) %>% 
  filter(country %in% c("Argentina", "Brazil", "Canada", "Chile", "Mexico", "Uruguay", "US")) %>% 
  mutate(winery = fct_reorder(winery, desc(points_avg_winery))) %>% 
  filter(as.numeric(winery) <= 20) %>% 
  arrange(winery) %>% 
  plot_ly(
    x = ~winery, y = ~points, color = ~factor(winery),
    type = "box", colors = "viridis") %>%
  layout(
    xaxis = list(title = "American Wineries"),
    yaxis = list(title = "Wine Points"),
    title = "Top 20 American Wineries: Highest Professional Recognition")
```

<br/>

### Bottom 20 American Wineries

```{r Bottom 20 American Wineries Box Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(points, country, winery, variety, points_avg_variety, points_avg_winery) %>% 
  filter(country %in% c("Argentina", "Brazil", "Canada", "Chile", "Mexico", "Uruguay", "US")) %>% 
  mutate(winery = fct_reorder(winery, points_avg_winery)) %>% 
  filter(as.numeric(winery) <= 20) %>% 
  arrange(winery) %>% 
  plot_ly(
    x = ~winery, y = ~points, color = ~factor(winery),
    type = "box", colors = "viridis") %>%
  layout(
    xaxis = list(title = "American Wineries"),
    yaxis = list(title = "Wine Points"),
    title = "Bottom American US Wineries: Lowest Professional Recognition")
```

<br/>

### Top 10 Grapes for American Wines

```{r Most Favorable American Grapes Violin Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(points, country, winery, variety, points_med_variety, points_med_winery) %>% 
  filter(country %in% c("Argentina", "Brazil", "Canada", "Chile", "Mexico", "Uruguay", "US")) %>% 
  mutate(variety = fct_reorder(variety, desc(points_med_variety))) %>% 
  filter(as.numeric(variety) <= 10) %>% 
  arrange(variety) %>% 
  plot_ly(
    x = ~variety, y = ~points, color = ~factor(variety),
    type = "violin", colors = "viridis") %>%
  layout(
    xaxis = list(title = "Grapes for American Wines"),
    yaxis = list(title = "Wine Points"),
    title = "Most Favorable 10 Grapes for American Wines: Highest Professional Recognition")
```

<br/>

### Bottom 10 Grapes for American Wines

```{r Least Favorable American Grapes Violin Plot, message = FALSE, warning = FALSE}
load("./data/wine150_tidy")

wine150_tidy %>% 
  select(points, country, winery, variety, points_med_variety, points_med_winery) %>% 
  filter(country %in% c("Argentina", "Brazil", "Canada", "Chile", "Mexico", "Uruguay", "US")) %>% 
  mutate(variety = fct_reorder(variety, points_med_variety)) %>% 
  filter(as.numeric(variety) <= 10) %>% 
  arrange(variety) %>% 
  plot_ly(
    x = ~variety, y = ~points, color = ~factor(variety),
    type = "violin", colors = "viridis") %>%
  layout(
    xaxis = list(title = "Grapes for American Wines"),
    yaxis = list(title = "Wine Points"),
    title = "Least Favorable 10 Grapes for American Wines: Lowest Professional Recognition")
```

